name: Tests

on:
  schedule:
    - cron: "26 5 * * *" # Every day, 05:26 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  daily-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Installing poetry
        run: pipx install poetry

      - name: Inatalling dependencies
        run: | 
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: Running provider tests
        run: poetry run python -m unittest -v
