name: Tests

on:
  schedule:
    - cron: "26 5 * * *" # Every day, 05:26 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  daily-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Installing poetry
        run: pipx install poetry

      - name: Inatalling dependencies
        run: poetry install

      - name: Formatting the code with black
        run: black syncedlyrics

      - name: Running provider tests
        run: python -m unittest -v
